version: "2"
volumes:
  pgdata:
services:
  postgres:
    image: "sophox/postgis"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres_conn
    ports:
      - "5432"
    env_file: .env
  import-natural-earth:
    image: "openmaptiles/import-natural-earth:${TOOLS_VERSION}"
    env_file: .env
    networks:
      - postgres_conn
  import-water:
    image: "openmaptiles/import-water:${TOOLS_VERSION}"
    env_file: .env
    networks:
      - postgres_conn
  import-lakelines:
    image: "openmaptiles/import-lakelines:${TOOLS_VERSION}"
    env_file: .env
    networks:
      - postgres_conn
  import-osm:
    image: "openmaptiles/import-osm:${TOOLS_VERSION}-imposm-0.8.1"
    env_file: .env
    environment:
      DIFF_MODE: ${DIFF_MODE}
    networks:
      - postgres_conn
    volumes:
      - ./data:/import
      - ./build:/mapping
      - ./cache:/cache
  import-osm-diff:
    image: "openmaptiles/import-osm:${TOOLS_VERSION}"
    env_file: .env
    command: ./import_diff.sh
    environment:
      DIFF_MODE: ${DIFF_MODE}
    networks:
      - postgres_conn
    volumes:
      - ./data:/import
      - ./build:/mapping
      - ./cache:/cache
  update-osm:
    image: "openmaptiles/import-osm:${TOOLS_VERSION}"
    env_file: .env
    environment:
      DIFF_MODE: ${DIFF_MODE}
    command: ./import_update.sh
    networks:
      - postgres_conn
    volumes:
      - ./data:/import
      - ./build:/mapping
      - ./cache:/cache
  openmaptiles-tools:
    image: "openmaptiles/openmaptiles-tools:${TOOLS_VERSION}"
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - .:/tileset
      - ./data:/import
      - ./build:/sql
  openmaptiles-tools-latest:
    # This target exists for experimental tools that have not yet been published.
    # Do not use this for production.
    image: "openmaptiles/openmaptiles-tools:latest"
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - .:/tileset
      - ./data:/import
      - ./build:/sql
  generate-changed-vectortiles:
    image: "openmaptiles/generate-vectortiles:${TOOLS_VERSION}"
    command: ./export-list.sh
    volumes:
      - ./data:/export
      - ./build/openmaptiles.tm2source:/tm2source
    networks:
      - postgres_conn
    env_file: .env
  generate-vectortiles:
    image: "openmaptiles/generate-vectortiles:${TOOLS_VERSION}"
    volumes:
      - ./data:/export
      - ./build/openmaptiles.tm2source:/tm2source
    networks:
      - postgres_conn
    env_file: .env
    environment:
      BBOX: ${BBOX}
      MIN_ZOOM: ${MIN_ZOOM}
      MAX_ZOOM: ${MAX_ZOOM}
  postserve:
    image: "openmaptiles/openmaptiles-tools:${TOOLS_VERSION}"
    command: postserve openmaptiles.yaml --verbose
    env_file: .env
    networks:
      - postgres_conn
    ports:
      - "8090:8090"
    volumes:
      - .:/tileset

networks:
  postgres_conn:
    driver: bridge
