version: "2"
volumes:
  pgdata:
services:
  postgres:
    image: "openmaptiles/postgis:${TOOLS_VERSION}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres_conn
    ports:
      - "5432"
    env_file: .env
  import-natural-earth:
    image: "openmaptiles/import-natural-earth:${TOOLS_VERSION}"
    env_file: .env
    networks:
      - postgres_conn
  import-water:
    image: "openmaptiles/import-water:${TOOLS_VERSION}"
    env_file: .env
    networks:
      - postgres_conn
  import-lakelines:
    image: "openmaptiles/import-lakelines:${TOOLS_VERSION}"
    env_file: .env
    networks:
      - postgres_conn
  import-osm:
    image: "openmaptiles/openmaptiles-tools:build-5.0-dev"
    env_file: .env
    environment:
      DIFF_MODE: ${DIFF_MODE}
    networks:
      - postgres_conn
    volumes:
      - ./data:/import
      - ./build:/mapping
      - ./cache:/cache
  import-osm-diff:
    image: "openmaptiles/openmaptiles-tools:build-5.0-dev"
    env_file: .env
    command: ./import_diff.sh
    environment:
      DIFF_MODE: ${DIFF_MODE}
    networks:
      - postgres_conn
    volumes:
      - ./data:/import
      - ./build:/mapping
      - ./cache:/cache
  update-osm:
    image: "openmaptiles/openmaptiles-tools:build-5.0-dev"
    env_file: .env
    environment:
      DIFF_MODE: ${DIFF_MODE}
    command: ./import_update.sh
    networks:
      - postgres_conn
    volumes:
      - ./data:/import
      - ./build:/mapping
      - ./cache:/cache
  openmaptiles-tools:
    image: "openmaptiles/openmaptiles-tools:build-5.0-dev"
    env_file: .env
    environment:
      # Must match the version of this file (first line)
      # download-osm will use it when generating a composer file
      MAKE_DC_VERSION: "2.3"
      # Allow DIFF_MODE to be overwritten from shell
      DIFF_MODE: ${DIFF_MODE}
    networks:
      - postgres_conn
    volumes:
      - .:/tileset
      - ./data:/import
      - ./build:/sql
      - ./build:/mapping
      - ./cache:/cache
  openmaptiles-tools-latest:
    # This target exists for experimental tools that have not yet been published.
    # Do not use this for production.
    image: "openmaptiles/openmaptiles-tools:latest"
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - .:/tileset
      - ./data:/import
      - ./build:/sql
  generate-changed-vectortiles:
    image: "openmaptiles/generate-vectortiles:${TOOLS_VERSION}"
    command: ./export-list.sh
    volumes:
      - ./data:/export
      - ./build/openmaptiles.tm2source:/tm2source
    networks:
      - postgres_conn
    env_file: .env
  generate-vectortiles:
    image: "openmaptiles/generate-vectortiles:${TOOLS_VERSION}"
    volumes:
      - ./data:/export
      - ./build/openmaptiles.tm2source:/tm2source
    networks:
      - postgres_conn
    env_file: .env
    environment:
      BBOX: ${BBOX}
      MIN_ZOOM: ${MIN_ZOOM}
      MAX_ZOOM: ${MAX_ZOOM}
  postserve:
    image: "openmaptiles/openmaptiles-tools:${TOOLS_VERSION}"
    command: postserve openmaptiles.yaml --verbose --serve=http://nginx/data/v3/
    env_file: .env
    networks:
      - postgres_conn
    ports:
      - "8090:8090"
    volumes:
      - .:/tileset

networks:
  postgres_conn:
    driver: bridge
